### ISSUE TITLE
[Server]Настройки порта

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#1]
Необходимо добавить функционал настройки порта для сервера.

**Comment by Veleri** [comment]
Issue is corrected.
 Изменение в модели:commit-[f97b310](https://github.com/kostyansasha/Lab2_Messenger/commit/f97b310404063daa135b9d19da69df9747c11b04)
 Изменения на сервере:commit- [c4db8a3](https://github.com/kostyansasha/Lab2_Messenger/commit/c4db8a3f572174778b0117003a6bb5e2065ce6bf)
