### ISSUE TITLE
[Client]Запрет изменения логина пользователя

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#10]
Нужно запретить возможность изменения пользователем его логина (сделать поле read only). Т.к. это может привести к множеству неудобностей и потенциальных багов.

**Comment by Miroshni4enko** [comment]
Запретить нужно только изменения логина или пароля тоже?

**Comment by das13** [comment]
Я думаю, что запреттить достаточно изменение только логина :-)
Иначе получится не логично
