### ISSUE TITLE
[Server]Ошибка при закрытии приложения сервера

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#11]
Закрывая окно сервера при запущенном (Start) сервере получаем ошибку **в журнале ошибок**:

> ERROR ControllerServer:210 - Server GUI: 
> java.net.SocketException: socket closed
>     at java.net.DualStackPlainSocketImpl.accept0(Native Method)
>     at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
>     at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
>     at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
>     at java.net.ServerSocket.implAccept(ServerSocket.java:530)
>     at java.net.ServerSocket.accept(ServerSocket.java:498)
>     at server.controller.ControllerServer.run(ControllerServer.java:226)
>     at server.view.ServerView.run(ServerView.java:168)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by Veleri** [comment]
Issue is corrected. Commit: [2f5fb34](https://github.com/kostyansasha/Lab2_Messenger/commit/2f5fb3493ebfff3e450195da67b22ed8a0a575d9)
