### ISSUE TITLE
[Server][Feature]Отмена запуска GUI сервера

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#12]
Добавить параметр для отмены запуска GUI сервера

**Comment by Veleri** [comment]
Issue is corrected.
Изменение в модели:commit-[2a87cf2](https://github.com/kostyansasha/Lab2_Messenger/commit/2a87cf2019ae4fd91bd46130237b21a5ad80913a)
Изменения на сервере:commit- [eb23729](https://github.com/kostyansasha/Lab2_Messenger/commit/eb2372912a807900cafac9d228373afbcf35db13)
