### ISSUE TITLE
[Client]Настройки порта и URL

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#2]
Необходимо добавить функционал настройки порта и URL для клиента.

**Comment by Miroshni4enko** [comment]
То есть мне надо будет сделать окно в которое пользователь сможет ввести порт, ip и если он будет правильным(подойдет для конекта с сервером) продолжать роботу, если нет сообщения об ошибке. Или надо как то по другому?

**Comment by das13** [comment]
Давай сделаем так.

**Comment by Miroshni4enko** [comment]
я сделал так что по умолчанию порт 1506 и URL localhost, но если они не подойдут появиться окно для ввода других порта и url, потому что каждый раз вводить это накладно
