### ISSUE TITLE
[Client]Имя пользователя на вкладке

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#3]
На вкладке приватного чата необходимо писать имя пользователя, с которым установлен приватный чат (например "**Private with User2**"), а также активировать эту вкладку после сразу после создания чата.

**Comment by Miroshni4enko** [comment]
Я решил, что оптимальным вариантом при создании приватного чата будет появления окна в котором пользователь введет название чата, которое потом будет передаваться его собеседникам + в запросе на создание чата у собеседника будет видно кто создал чат

**Comment by das13** [comment]
Наверное это самое оптимальное решение.
