### ISSUE TITLE
[Server]Оповещение клиентов о штатной остановке/перезапуске

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#4]
Когда сервер останавливается или перезапускается в штатном режиме, нужно об этом оповещать клиентов. Например **Server is restarting now**

**Comment by Veleri** [comment]
Issue is corrected. Commit: [405a9ce](https://github.com/kostyansasha/Lab2_Messenger/commit/405a9cea856fb13f704d322867579fce6b30e469)
При остановке сервера, клиентам рассылается команда "Stop" + оповещение в общий чат.
