### ISSUE TITLE
[Server]Сообщение о блокировании (ban) пользователя

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#5]
Когда пользователь забанен/разбанен, ему нужно об этом сообщить, а также вывести сообщение в общий чат.

**Comment by Veleri** [comment]
Issue is corrected. 
Если пользователь онлайн во время команды "ban/unban", сервер сообщает пользователю об этом. (строки 377-386;406-413). Сообщение в общий чат добавлено в commit: [da37d42](https://github.com/kostyansasha/Lab2_Messenger/commit/da37d4274a3b11bea584d2138e1e81d5e91990d4).
