### ISSUE TITLE
[Users]Функционал для заблокированного пользователя

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#6]
Когда забаненный пользователь входит в систему, он должен получать список пользователей (сейчас не получает), но не может создавать чаты и передавать сообщения (соответствующие контролы должны быть не активны).
После разбанивания функционал должен вернуться.

_(Этот функционал можно обсудить)_

**Comment by Miroshni4enko** [comment]
По моему, весь функционал перечисленный выше и так уже рабочий ?

**Comment by das13** [comment]
Перепроверил, вроде да.
Закрываю.
