### ISSUE TITLE
[Client]Закрытие приватных вкладок

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#8]
Если пользователь выходит из системы, нужно (как минимум) предупреждать об этом его собеседника и закрывать вкладки приватного чата у этого пользователя и у его собеседника.

**Comment by Miroshni4enko** [comment]
Думаю закрытие вкладки у собеседника будет лишним, так как он может быть не один.

**Comment by das13** [comment]
Согласен. А если на вкладке остался только один активный пользователь, такая вкладка нужна? По-моему - нет.

**Comment by Miroshni4enko** [comment]
согласен, не нужна)

**Comment by Miroshni4enko** [comment]
хотя нет, а вдруг понадобиться сама переписка.  Мне кажется лучше пусть пользователь сам решает .
