### ISSUE TITLE
[Client]Возможность реконнекта клиента

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab2_Messenger#9]
Если остановить сервер и с клиента послать сообщение, то после предупреждения "**Server is Down**" клиент закрывается. Дружественнее при такой ситуации сделать возможность реконнекта.

_(Это можно обсудить)_

**Comment by Miroshni4enko** [comment]
Можно не закрывать форму, попробовать поймать все ошибки. А именно реконнект я даже не знаю как реализовать, так как там задействованы потоки. Легче приложения рестартонуть, а там теперь если нету подключения есть возможность поменять  url и port, и даже если не подключишься ошибки не будет. Может есть идеи для реализации?

**Comment by Veleri** [comment]
А если попробовать закрыть сокет и потоки, а при реконекте вызывать метод boolean connectToServer() и в зависимости от результата действовать(он же создает новый сокет и соответственно потоки)? Нужно еще учесть, что после падения сервера клиенту нужно заново проходить авторизацию.

**Comment by Veleri** [comment]
При плановом отключении сервер рассылает клиентам команду и сообщение "STOP"
